# 使用官方的 Python 作為基礎映像檔
FROM python:3.10-slim

# 設定工作目錄
WORKDIR /app

# 複製 requirements.txt 並安裝 Python 套件
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 複製應用程式的程式碼
COPY app/ .

# 暴露應用程式的埠號
EXPOSE 5000

# 定義環境變數
ENV FLASK_APP=FundamentalStockAnalysis.py
ENV FLASK_RUN_HOST=0.0.0.0

# 啟動應用程式
CMD ["flask", "run"]