version: '3.8'

services:
  app:
    build: .
    container_name: fundamental_stock_analysis_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - NLP_API_URL=http://nlp_module:5001/analyze
    depends_on:
      - mongo
      - nlp_module

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nlp_module:
    image: your_nlp_module_image  # 替換為你的 NLP 模組映像檔名稱
    container_name: nlp_module
    ports:
      - "5001:5001"
    # 根據你的 NLP 模組需求新增環境變數或其他設定
    environment:
      - SOME_ENV_VAR=your_value

volumes:
  mongo_data: